#include "gain_ground/contract_types.h"
#include "gground_functions.h"
#include <cstdint>

namespace gain_ground::translated { namespace {
constexpr std::uint16_t P=1,S=3,T=5,W=0xffff; constexpr std::uint32_t M=0x3ffff;
void pf(ExecutionHost&h,std::uint32_t a){(void)h.read_memory_word(P,a,W);} std::uint16_t rw(ExecutionHost&h,std::uint32_t a){return h.read_memory_word(P,a,W);} std::uint16_t rs(ExecutionHost&h,std::uint32_t a){return h.read_memory_word(S,a&M,W);} void ws(ExecutionHost&h,std::uint32_t a,std::uint16_t v){h.write_memory_word(S,a&M,v,W);}
void logicw(CpuRegisters&r,std::uint16_t v){std::uint16_t f=r.status&0x10;if(v&0x8000)f|=8;if(!v)f|=4;r.status=static_cast<std::uint16_t>((r.status&~0x1f)|f);} void logicl(CpuRegisters&r,std::uint32_t v){std::uint16_t f=r.status&0x10;if(v&0x80000000)f|=8;if(!v)f|=4;r.status=static_cast<std::uint16_t>((r.status&~0x1f)|f);}
void addw(CpuRegisters&r,std::uint32_t n){auto a=static_cast<std::uint16_t>(r.data[n]),v=static_cast<std::uint16_t>(a+a);bool c=std::uint32_t(a)+a>0xffff,o=((~(a^a)&(a^v))&0x8000)!=0;std::uint16_t f=0;if(c)f|=0x11;if(v&0x8000)f|=8;if(!v)f|=4;if(o)f|=2;r.data[n]=(r.data[n]&0xffff0000)|v;r.status=static_cast<std::uint16_t>((r.status&~0x1f)|f);}
void incw(CpuRegisters&r){auto a=static_cast<std::uint16_t>(r.data[7]),v=static_cast<std::uint16_t>(a+1);std::uint16_t f=0;if(v&0x8000)f|=8;if(!v)f|=4;if(a==0x7fff)f|=2;r.data[7]=(r.data[7]&0xffff0000)|v;r.status=static_cast<std::uint16_t>((r.status&~0x0f)|f);}
FunctionResult call29(FunctionContext&c,std::uint32_t site,std::uint32_t ret){auto&h=*c.host;auto&r=c.registers;r.address[7]-=4;ws(h,r.address[7],static_cast<std::uint16_t>(ret>>16));ws(h,r.address[7]+2,static_cast<std::uint16_t>(ret));pf(h,0x1c28);pf(h,0x1c2a);return h.call_function(29,0,0xff,2,site,0x1c28,c);}
void put(FunctionContext&c,std::uint32_t disp,bool post){auto&r=c.registers;auto&h=*c.host;h.write_memory_word(T,(r.address[3]+disp)&M,static_cast<std::uint16_t>(r.data[7]),W);if(post)r.address[3]+=2;logicw(r,static_cast<std::uint16_t>(r.data[7]));}
FunctionResult loop(FunctionContext&c,std::uint32_t site){auto&r=c.registers;pf(*c.host,0x1a8c);pf(*c.host,0x1a8e);r.program_counter=0x1a8c;auto z=c.host->call_function(28,0,0xff,1,site,0x1a8c,c);return z.status==TranslationStatus::complete?FunctionResult::complete(4,0x1a8c):z;}
}
FunctionResult cpu_a_expand_record_words_to_output(FunctionContext&c) noexcept {if(!c.host)return{TranslationStatus::contract_violation,0,c.registers.program_counter};auto&h=*c.host;auto&r=c.registers;r.data[0]=0;logicl(r,0);pf(h,0x1a90);auto v=rw(h,r.address[0]);r.address[0]+=2;r.data[0]=(r.data[0]&0xffff0000)|v;logicw(r,v);pf(h,0x1a92);if(!v){pf(h,0x1a94);auto sp=r.address[7]&M;auto target=(std::uint32_t(rs(h,sp))<<16)|rs(h,sp+2);r.address[7]+=4;pf(h,target);pf(h,target+2);r.program_counter=target;return FunctionResult::complete(1,target);}pf(h,0x1a94);
r.data[1]=(r.data[1]&0xffff0000)|v;logicw(r,v);pf(h,0x1a96);auto before=r.data[0];r.data[0]<<=3;logicl(r,r.data[0]);r.status=static_cast<std::uint16_t>((r.status&~2)|((((before^r.data[0])&0x80000000)!=0)?2:0));pf(h,0x1a98);r.address[1]=r.data[0];pf(h,0x1a9a);addw(r,1);pf(h,0x1a9c);pf(h,0x1a9e);
if(static_cast<std::int16_t>(r.data[1])>=0){pf(h,0x1aa0);addw(r,1);pf(h,0x1aa2);pf(h,0x1aa4);if(static_cast<std::int16_t>(r.data[1])>=0){pf(h,0x1aec);pf(h,0x1aee);auto z=call29(c,0x1aec,0x1af0);if(z.status!=TranslationStatus::complete)return z;put(c,0x80,false);pf(h,0x1af4);incw(r);pf(h,0x1af6);r.address[3]+=2;pf(h,0x1af8);pf(h,0x1afa);return loop(c,0x1af8);}pf(h,0x1aa6);addw(r,1);pf(h,0x1aa8);pf(h,0x1aaa);if(static_cast<std::int16_t>(r.data[1])<0){pf(h,0x1aac);pf(h,0x1aae);auto z=call29(c,0x1aac,0x1ab0);if(z.status!=TranslationStatus::complete)return z;r.address[1]+=8;pf(h,0x1ab2);z=call29(c,0x1ab2,0x1ab6);if(z.status!=TranslationStatus::complete)return z;put(c,0,true);pf(h,0x1ab8);incw(r);pf(h,0x1aba);put(c,0x7e,false);pf(h,0x1abe);incw(r);pf(h,0x1ac0);pf(h,0x1ac2);return loop(c,0x1ac0);}}
pf(h,0x1ac4);pf(h,0x1ac6);for(std::uint32_t site=0x1ac4;site<=0x1ad0;site+=4){auto z=call29(c,site,site+4);if(z.status!=TranslationStatus::complete)return z;}put(c,0,true);pf(h,0x1ad8);incw(r);pf(h,0x1ada);put(c,0,true);pf(h,0x1adc);incw(r);pf(h,0x1ade);pf(h,0x1ae0);put(c,0x7c,false);incw(r);pf(h,0x1ae2);pf(h,0x1ae4);pf(h,0x1ae6);put(c,0x7e,false);incw(r);pf(h,0x1ae8);pf(h,0x1aea);return loop(c,0x1ae8);}
} // namespace gain_ground::translated
