cmake_minimum_required(VERSION 3.24)
if(NOT SOURCE_ROOT)
    set(SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(files "")
foreach(directory src include generated)
    file(GLOB_RECURSE found "${SOURCE_ROOT}/${directory}/*")
    foreach(path IN LISTS found)
        if(path MATCHES "\\.(c|cc|cpp|cxx|h|hh|hpp|hxx|inc|inl|ipp)$")
            list(APPEND files "${path}")
        endif()
    endforeach()
endforeach()
set(failures "")
set(maximum 0)
foreach(path IN LISTS files)
    file(READ "${path}" data)
    string(REGEX REPLACE "[^\n]" "" newlines "${data}")
    string(LENGTH "${newlines}" lines)
    if(NOT data STREQUAL "" AND NOT data MATCHES "\n$")
        math(EXPR lines "${lines} + 1")
    endif()
    if(lines GREATER maximum)
        set(maximum ${lines})
    endif()
    if(lines GREATER 400)
        file(RELATIVE_PATH relative "${SOURCE_ROOT}" "${path}")
        list(APPEND failures "${relative}: ${lines}")
    endif()
endforeach()
if(failures)
    list(JOIN failures "\n" details)
    message(FATAL_ERROR "Native source exceeds 400 physical lines:\n${details}")
endif()
list(LENGTH files count)
message(STATUS "${count} native source files; maximum ${maximum} lines; zero exceptions")
