#pragma once
// Generated by scripts/Generate-GapTranslations.py. Source-owned registration
// of translated routines no captured run reached. Do not edit by hand.
#include "gain_ground/contract_types.h"
#include <array>

namespace gain_ground::translated {
FunctionResult cpu_b_stage_gap_014016(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01405a(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_014082(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0140c6(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0140ee(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01412c(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_014164(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0141d6(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01420e(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0142ca(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0142da(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0142fc(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01437e(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01bfce(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01c02e(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01cfae(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01d04e(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01e75a(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01e7fa(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01ee78(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01ef12(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01ff14(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_01ff88(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_020046(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0200e0(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_02013c(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0201ba(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_020228(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_02029c(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_02034c(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0209fe(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_020abe(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_020e34(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_021698(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0217d4(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_02184a(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_021854(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0218ca(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0218d4(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_02194a(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_021954(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0219ca(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_021ba0(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_021c16(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0227ba(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_02290e(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0231fa(FunctionContext &) noexcept;
FunctionResult cpu_b_stage_gap_0233b0(FunctionContext &) noexcept;
}

namespace gain_ground::stage_gap_registry {
inline constexpr std::array<FunctionContract, 48> kEntries{{
    FunctionContract{649U, 1U, 0x72U, false, true, 0x14016U, 0x14016U, 0x14081U, 108U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_014016", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_014016},
    FunctionContract{678U, 1U, 0x72U, false, true, 0x1405aU, 0x1405aU, 0x14081U, 40U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01405a", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01405a},
    FunctionContract{650U, 1U, 0x72U, false, true, 0x14082U, 0x14082U, 0x140edU, 108U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_014082", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_014082},
    FunctionContract{679U, 1U, 0x72U, false, true, 0x140c6U, 0x140c6U, 0x140edU, 40U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0140c6", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0140c6},
    FunctionContract{651U, 1U, 0x72U, false, true, 0x140eeU, 0x140eeU, 0x14163U, 118U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0140ee", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0140ee},
    FunctionContract{680U, 1U, 0x72U, false, true, 0x1412cU, 0x1412cU, 0x14163U, 56U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01412c", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01412c},
    FunctionContract{669U, 1U, 0x72U, false, true, 0x14164U, 0x14164U, 0x1420dU, 170U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_014164", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_014164},
    FunctionContract{692U, 1U, 0x72U, false, true, 0x141d6U, 0x141d6U, 0x1420dU, 56U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0141d6", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0141d6},
    FunctionContract{652U, 1U, 0x72U, false, true, 0x1420eU, 0x1420eU, 0x142c9U, 188U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01420e", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01420e},
    FunctionContract{681U, 1U, 0x72U, false, true, 0x142caU, 0x142caU, 0x142fbU, 50U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0142ca", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0142ca},
    FunctionContract{682U, 1U, 0x72U, false, true, 0x142daU, 0x142daU, 0x142fbU, 34U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0142da", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0142da},
    FunctionContract{653U, 1U, 0x72U, false, true, 0x142fcU, 0x142fcU, 0x1437dU, 130U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0142fc", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0142fc},
    FunctionContract{668U, 1U, 0x72U, false, true, 0x1437eU, 0x1437eU, 0x143f7U, 122U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01437e", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01437e},
    FunctionContract{696U, 1U, 0x72U, false, true, 0x1bfceU, 0x1bfceU, 0x1da19U, 6732U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01bfce", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01bfce},
    FunctionContract{688U, 1U, 0x72U, false, true, 0x1c02eU, 0x1c02eU, 0x1d9e9U, 6588U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01c02e", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01c02e},
    FunctionContract{686U, 1U, 0x72U, false, true, 0x1cfaeU, 0x1cfaeU, 0x1d9e9U, 2620U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01cfae", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01cfae},
    FunctionContract{685U, 1U, 0x72U, false, true, 0x1d04eU, 0x1d04eU, 0x1da19U, 2508U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01d04e", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01d04e},
    FunctionContract{683U, 1U, 0x72U, false, true, 0x1e75aU, 0x1e75aU, 0x1e7f9U, 160U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01e75a", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01e75a},
    FunctionContract{687U, 1U, 0x72U, false, true, 0x1e7faU, 0x1e7faU, 0x1e8d9U, 224U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01e7fa", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01e7fa},
    FunctionContract{666U, 1U, 0x72U, false, true, 0x1ee78U, 0x1ee78U, 0x1eeb5U, 62U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01ee78", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01ee78},
    FunctionContract{695U, 1U, 0x72U, false, true, 0x1ef12U, 0x1ef12U, 0x1ef61U, 80U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01ef12", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01ef12},
    FunctionContract{674U, 1U, 0x72U, false, true, 0x1ff14U, 0x1ff14U, 0x1ff87U, 116U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01ff14", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01ff14},
    FunctionContract{675U, 1U, 0x72U, false, true, 0x1ff88U, 0x1ff88U, 0x20045U, 190U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_01ff88", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_01ff88},
    FunctionContract{654U, 1U, 0x72U, false, true, 0x20046U, 0x20046U, 0x200dfU, 154U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_020046", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_020046},
    FunctionContract{655U, 1U, 0x72U, false, true, 0x200e0U, 0x200e0U, 0x2013bU, 92U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0200e0", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0200e0},
    FunctionContract{656U, 1U, 0x72U, false, true, 0x2013cU, 0x2013cU, 0x201b9U, 126U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_02013c", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_02013c},
    FunctionContract{657U, 1U, 0x72U, false, true, 0x201baU, 0x201baU, 0x20227U, 110U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0201ba", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0201ba},
    FunctionContract{684U, 1U, 0x72U, false, true, 0x20228U, 0x20228U, 0x2029bU, 116U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_020228", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_020228},
    FunctionContract{676U, 1U, 0x72U, false, true, 0x2029cU, 0x2029cU, 0x2034bU, 176U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_02029c", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_02029c},
    FunctionContract{677U, 1U, 0x72U, false, true, 0x2034cU, 0x2034cU, 0x203c1U, 118U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_02034c", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_02034c},
    FunctionContract{673U, 1U, 0x72U, false, true, 0x209feU, 0x209feU, 0x20a5dU, 96U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0209fe", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0209fe},
    FunctionContract{670U, 1U, 0x72U, false, true, 0x20abeU, 0x20abeU, 0x20b19U, 92U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_020abe", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_020abe},
    FunctionContract{658U, 1U, 0x72U, false, true, 0x20e34U, 0x20e34U, 0x20e8fU, 92U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_020e34", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_020e34},
    FunctionContract{659U, 1U, 0x72U, false, true, 0x21698U, 0x21698U, 0x21713U, 124U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_021698", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_021698},
    FunctionContract{660U, 1U, 0x72U, false, true, 0x217d4U, 0x217d4U, 0x21853U, 128U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0217d4", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0217d4},
    FunctionContract{689U, 1U, 0x72U, false, true, 0x2184aU, 0x2184aU, 0x21853U, 10U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_02184a", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_02184a},
    FunctionContract{667U, 1U, 0x72U, false, true, 0x21854U, 0x21854U, 0x218d3U, 128U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_021854", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_021854},
    FunctionContract{691U, 1U, 0x72U, false, true, 0x218caU, 0x218caU, 0x218d3U, 10U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0218ca", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0218ca},
    FunctionContract{671U, 1U, 0x72U, false, true, 0x218d4U, 0x218d4U, 0x21953U, 128U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0218d4", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0218d4},
    FunctionContract{693U, 1U, 0x72U, false, true, 0x2194aU, 0x2194aU, 0x21953U, 10U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_02194a", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_02194a},
    FunctionContract{672U, 1U, 0x72U, false, true, 0x21954U, 0x21954U, 0x219d3U, 128U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_021954", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_021954},
    FunctionContract{694U, 1U, 0x72U, false, true, 0x219caU, 0x219caU, 0x219d3U, 10U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0219ca", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0219ca},
    FunctionContract{661U, 1U, 0x72U, false, true, 0x21ba0U, 0x21ba0U, 0x21c1fU, 128U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_021ba0", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_021ba0},
    FunctionContract{690U, 1U, 0x72U, false, true, 0x21c16U, 0x21c16U, 0x21c1fU, 10U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_021c16", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_021c16},
    FunctionContract{662U, 1U, 0x72U, false, true, 0x227baU, 0x227baU, 0x227dfU, 38U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0227ba", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0227ba},
    FunctionContract{663U, 1U, 0x72U, false, true, 0x2290eU, 0x2290eU, 0x22957U, 74U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_02290e", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_02290e},
    FunctionContract{664U, 1U, 0x72U, false, true, 0x231faU, 0x231faU, 0x23209U, 16U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0231fa", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0231fa},
    FunctionContract{665U, 1U, 0x72U, false, true, 0x233b0U, 0x233b0U, 0x233bfU, 16U, 0U, 0U, "cpu-b", "72", "unverified", "retained-opcode-source", "implementation-first", "implemented-but-unverified", "cpu_b_stage_gap_0233b0", "native/src/translated/cpu_b_stage_gap_callbacks.cpp", &translated::cpu_b_stage_gap_0233b0},
}};

inline const FunctionContract *find(std::uint8_t cpu, std::uint8_t state, std::uint32_t address) noexcept {
    for (const auto &entry : kEntries)
        if (entry.cpu == cpu && entry.state == state && entry.address == address) return &entry;
    return nullptr;
}
} // namespace gain_ground::stage_gap_registry
